# Generated by Django 3.1.7 on 2021-03-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='nom',
            new_name='name',
        ),
    ]
